/**
 * Reading a Word document and a PDF.
 *
 * The upload form invited PDF and Word from the first release and nothing could
 * read either, so a customer uploading their product handbook (which is a PDF,
 * because every product handbook is a PDF) was told no extractor was
 * configured. The first thing a new customer does was the first thing that
 * failed.
 *
 * The fixtures are built here rather than committed. A binary fixture in a
 * repository is a file nobody can review, and one that was generated by the
 * code it tests proves only that the code agrees with itself. These are
 * assembled from the format specifications: a real zip of real Word XML, and a
 * real PDF with a real deflated content stream.
 */
import { describe, expect, it } from 'vitest';
import { deflateRawSync, deflateSync } from 'node:zlib';
import { DocxExtractor, PdfExtractor, looksReadable } from '@detent/awa-ingestion';

/** A minimal but genuine zip: local header, data, central directory, end record. */
function zipOf(name: string, contents: string): Buffer {
  const nameBytes = Buffer.from(name, 'utf8');
  const raw = Buffer.from(contents, 'utf8');
  const deflated = deflateRawSync(raw);
  const crc = crc32(raw);

  const local = Buffer.alloc(30);
  local.writeUInt32LE(0x04034b50, 0);
  local.writeUInt16LE(20, 4);            // version needed
  local.writeUInt16LE(8, 8);             // deflate
  local.writeUInt32LE(crc, 14);
  local.writeUInt32LE(deflated.length, 18);
  local.writeUInt32LE(raw.length, 22);
  local.writeUInt16LE(nameBytes.length, 26);

  const localRecord = Buffer.concat([local, nameBytes, deflated]);

  const central = Buffer.alloc(46);
  central.writeUInt32LE(0x02014b50, 0);
  central.writeUInt16LE(20, 6);
  central.writeUInt16LE(8, 10);
  central.writeUInt32LE(crc, 16);
  central.writeUInt32LE(deflated.length, 20);
  central.writeUInt32LE(raw.length, 24);
  central.writeUInt16LE(nameBytes.length, 28);
  central.writeUInt32LE(0, 42);          // offset of the local header

  const centralRecord = Buffer.concat([central, nameBytes]);

  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(1, 8);
  end.writeUInt16LE(1, 10);
  end.writeUInt32LE(centralRecord.length, 12);
  end.writeUInt32LE(localRecord.length, 16);

  return Buffer.concat([localRecord, centralRecord, end]);
}

const CRC_TABLE = Array.from({ length: 256 }, (_, n) => {
  let c = n;
  for (let k = 0; k < 8; k += 1) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  return c >>> 0;
});
function crc32(buffer: Buffer): number {
  let c = 0xffffffff;
  for (const byte of buffer) c = CRC_TABLE[(c ^ byte) & 0xff]! ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

const WORD_XML = `<?xml version="1.0" encoding="UTF-8"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>
<w:p><w:r><w:t>Detent price list, September 2026.</w:t></w:r></w:p>
<w:p><w:r><w:t>The subscription is nine pounds ninety nine a month.</w:t></w:r>`
  + `<w:r><w:t xml:space="preserve"> Each answer is fifty pence.</w:t></w:r></w:p>
<w:p><w:r><w:t>Returns are accepted within thirty days &amp; delivery is free over one hundred pounds.</w:t></w:r></w:p>
</w:body></w:document>`;

/** A genuine PDF with one page and one deflated content stream. */
function pdfOf(lines: readonly string[]): Buffer {
  const content = Buffer.from(
    `BT /F1 12 Tf 72 720 Td ${lines.map((line) => `(${line}) Tj T*`).join('\n')} ET`,
    'latin1',
  );
  const stream = deflateSync(content);
  const objects: Buffer[] = [
    Buffer.from('<< /Type /Catalog /Pages 2 0 R >>'),
    Buffer.from('<< /Type /Pages /Kids [3 0 R] /Count 1 >>'),
    Buffer.from('<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R >>'),
    Buffer.concat([
      Buffer.from(`<< /Length ${stream.length} /Filter /FlateDecode >>\nstream\n`),
      stream,
      Buffer.from('\nendstream'),
    ]),
  ];
  const parts: Buffer[] = [Buffer.from('%PDF-1.4\n')];
  objects.forEach((body, index) => {
    parts.push(Buffer.from(`${index + 1} 0 obj\n`), body, Buffer.from('\nendobj\n'));
  });
  parts.push(Buffer.from('trailer\n<< /Size 5 /Root 1 0 R >>\n%%EOF\n'));
  return Buffer.concat(parts);
}

describe('a Word document', () => {
  it('reads as the words that are in it', async () => {
    const bytes = zipOf('word/document.xml', WORD_XML);
    const { text } = await new DocxExtractor().extract(bytes);
    expect(text).toContain('Detent price list, September 2026.');
    expect(text).toContain('nine pounds ninety nine a month');
    // Two runs in one paragraph are one sentence, not two lines.
    expect(text).toContain('a month. Each answer is fifty pence.');
    // Entities are decoded, or the knowledge agent reads "&amp;" as a word.
    expect(text).toContain('thirty days & delivery');
    expect(text).not.toContain('<w:');
    expect(looksReadable(text)).toBe(true);
  });

  it('keeps paragraphs apart, because a price list flattened is unreadable', async () => {
    const { text } = await new DocxExtractor().extract(zipOf("word/document.xml", WORD_XML));
    expect(text.split('\n').filter(Boolean).length).toBeGreaterThanOrEqual(3);
  });

  it('says what is wrong with a file that is not one', async () => {
    const notWord = zipOf('some/other.xml', '<x>hello</x>');
    await expect(new DocxExtractor().extract(notWord)).rejects.toThrow(/Word document/i);
  });
});

describe('a PDF', () => {
  const lines = [
    'Detent price list, September 2026.',
    'The subscription is nine pounds ninety nine a month.',
    'Each answer costs fifty pence, capped at three pounds a conversation.',
  ];

  it('reads the text out of a compressed content stream', async () => {
    const { text } = await new PdfExtractor().extract(pdfOf(lines));
    for (const line of lines) expect(text).toContain(line);
    expect(looksReadable(text)).toBe(true);
  });

  it('counts its pages', async () => {
    const { pageCount } = await new PdfExtractor().extract(pdfOf(lines));
    expect(pageCount).toBe(1);
  });

  it('refuses a file that is named .pdf and is not one', async () => {
    await expect(new PdfExtractor().extract(Buffer.from('just some text')))
      .rejects.toThrow(/does not begin like one/i);
  });
});

describe('deciding whether the result is worth proposing', () => {
  it('accepts ordinary prose', () => {
    expect(looksReadable(
      'The subscription is nine pounds ninety nine a month and each answer is fifty pence.',
    )).toBe(true);
  });

  it('rejects a scan, which yields nothing at all', () => {
    expect(looksReadable('')).toBe(false);
    expect(looksReadable('  \n \n ')).toBe(false);
  });

  it('rejects a stream of coordinates, which is the failure that matters', () => {
    // Not an exception, which is why it needs catching here: a page of
    // punctuation proposed as knowledge is worse than an honest refusal.
    expect(looksReadable('0.24 0 0 0.24 72 720 Tm [( )-249( )] 1 0 0 1 0 0 cm /X0 Do Q')).toBe(false);
  });
});
