/**
 * Envelope encryption for credentials at rest (audit SEC-4).
 *
 * OAuth access tokens for every connected CRM of every tenant were held as
 * plain strings in a Map. The redaction layer keeps them out of logs; nothing
 * protected them at rest, so a heap dump or a core file exposed live
 * credentials for every tenant at once.
 *
 * The shape here is ordinary envelope encryption, and the reason for the shape
 * is the rotation story: a per-tenant data key is generated by a key management
 * service, used to encrypt one value, and stored only in its wrapped form
 * beside the ciphertext. Rotating the root key rewraps data keys without
 * touching ciphertext; revoking one tenant's key cannot read another's, because
 * a data key is never shared between tenants.
 *
 * `LocalKeyring` exists so a development or test deployment is encrypted too,
 * the failure mode where the secure path is the one nobody exercises is exactly
 * how plaintext ends up in production.
 */
import { createCipheriv, createDecipheriv, hkdfSync, randomBytes, timingSafeEqual } from 'node:crypto';

/** A credential as it is stored: ciphertext plus everything needed to unwrap it. */
export interface SealedValue {
  /** Format version, so a future algorithm change is a migration, not a guess. */
  readonly v: 1;
  /** Key management provider that produced the wrapped data key. */
  readonly provider: string;
  /** Identifier of the root key used, for rotation and for audit. */
  readonly keyId: string;
  /** Data key, wrapped by the root key. Base64url. */
  readonly wrappedKey: string;
  readonly iv: string;
  readonly ciphertext: string;
  readonly tag: string;
  readonly sealedAt: string;
}

export function isSealedValue(value: unknown): value is SealedValue {
  if (!value || typeof value !== 'object') return false;
  const candidate = value as Partial<SealedValue>;
  return candidate.v === 1 && typeof candidate.ciphertext === 'string' && typeof candidate.wrappedKey === 'string';
}

/**
 * The key management boundary. AWS KMS, GCP KMS and Azure Key Vault all
 * implement generate-data-key and decrypt; this is the two calls, named.
 */
export interface KeyProvider {
  readonly name: string;
  readonly keyId: string;
  /** A fresh 32-byte data key, returned in the clear and wrapped. */
  generateDataKey(tenantId: string): Promise<{ plaintext: Buffer; wrapped: string }>;
  unwrapDataKey(tenantId: string, wrapped: string): Promise<Buffer>;
}

/**
 * Local provider: the root key lives in the process environment and data keys
 * are wrapped with AES-256-GCM under a per-tenant subkey derived by HKDF.
 *
 * The per-tenant derivation matters: it means the wrapped key for tenant A
 * cannot be unwrapped in tenant B's context even if the ciphertext is moved
 * between rows, which is the mistake an attacker with database write access
 * would otherwise try.
 */
export class LocalKeyProvider implements KeyProvider {
  readonly name = 'local';
  readonly keyId: string;
  private readonly root: Buffer;

  constructor(rootKey: Buffer | string, keyId = 'local-dev') {
    const buffer = typeof rootKey === 'string' ? Buffer.from(rootKey, 'base64url') : rootKey;
    if (buffer.length < 32) {
      throw new Error('root key must be at least 32 bytes; refusing to encrypt with a weak key');
    }
    this.root = buffer;
    this.keyId = keyId;
  }

  static generateRootKey(): string {
    return randomBytes(32).toString('base64url');
  }

  private subkey(tenantId: string): Buffer {
    return Buffer.from(hkdfSync('sha256', this.root, Buffer.from('awa-tenant-kek'), Buffer.from(tenantId), 32));
  }

  async generateDataKey(tenantId: string): Promise<{ plaintext: Buffer; wrapped: string }> {
    const plaintext = randomBytes(32);
    const iv = randomBytes(12);
    const cipher = createCipheriv('aes-256-gcm', this.subkey(tenantId), iv);
    const sealed = Buffer.concat([cipher.update(plaintext), cipher.final()]);
    const tag = cipher.getAuthTag();
    const wrapped = Buffer.concat([iv, tag, sealed]).toString('base64url');
    return { plaintext, wrapped };
  }

  async unwrapDataKey(tenantId: string, wrapped: string): Promise<Buffer> {
    const raw = Buffer.from(wrapped, 'base64url');
    const iv = raw.subarray(0, 12);
    const tag = raw.subarray(12, 28);
    const body = raw.subarray(28);
    const decipher = createDecipheriv('aes-256-gcm', this.subkey(tenantId), iv);
    decipher.setAuthTag(tag);
    return Buffer.concat([decipher.update(body), decipher.final()]);
  }
}

export class Keyring {
  constructor(
    private readonly provider: KeyProvider,
    private readonly clock: () => string = () => new Date().toISOString(),
  ) {}

  get keyId(): string { return this.provider.keyId; }

  async seal(tenantId: string, plaintext: string): Promise<SealedValue> {
    const { plaintext: dataKey, wrapped } = await this.provider.generateDataKey(tenantId);
    const iv = randomBytes(12);
    const cipher = createCipheriv('aes-256-gcm', dataKey, iv);
    // The tenant id is authenticated but not encrypted: moving a ciphertext to
    // another tenant's row makes it undecryptable rather than readable.
    cipher.setAAD(Buffer.from(tenantId));
    const body = Buffer.concat([cipher.update(plaintext, 'utf8'), cipher.final()]);
    const value: SealedValue = {
      v: 1,
      provider: this.provider.name,
      keyId: this.provider.keyId,
      wrappedKey: wrapped,
      iv: iv.toString('base64url'),
      ciphertext: body.toString('base64url'),
      tag: cipher.getAuthTag().toString('base64url'),
      sealedAt: this.clock(),
    };
    dataKey.fill(0);
    return value;
  }

  async open(tenantId: string, sealed: SealedValue): Promise<string> {
    const dataKey = await this.provider.unwrapDataKey(tenantId, sealed.wrappedKey);
    const decipher = createDecipheriv('aes-256-gcm', dataKey, Buffer.from(sealed.iv, 'base64url'));
    decipher.setAAD(Buffer.from(tenantId));
    decipher.setAuthTag(Buffer.from(sealed.tag, 'base64url'));
    const plaintext = Buffer.concat([
      decipher.update(Buffer.from(sealed.ciphertext, 'base64url')),
      decipher.final(),
    ]).toString('utf8');
    dataKey.fill(0);
    return plaintext;
  }

  /**
   * Re-seal under the current root key. Rotation is a loop over stored values
   * calling this; ciphertext is rewritten, the plaintext never leaves memory.
   */
  async rewrap(tenantId: string, sealed: SealedValue): Promise<SealedValue> {
    return this.seal(tenantId, await this.open(tenantId, sealed));
  }
}

/** Constant-time comparison for secrets held as strings. */
export function secretEquals(a: string, b: string): boolean {
  const left = Buffer.from(a);
  const right = Buffer.from(b);
  if (left.length !== right.length) return false;
  return timingSafeEqual(left, right);
}
